"""
A2A Protocol Models
===================

Pydantic models for the Agent-to-Agent (A2A) protocol.
These models align with the A2A Protocol Specification v1.0.

The A2A protocol enables communication between AI agents using:
- Agent Cards for capability discovery
- Tasks for stateful work units
- Messages for communication
- Artifacts for task outputs
- Streaming for real-time updates

Reference: https://a2a-protocol.org/latest/specification/
"""

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


# =============================================================================
# Enums
# =============================================================================


class TaskState(str, Enum):
    """Defines the possible lifecycle states of a Task."""

    UNSPECIFIED = "TASK_STATE_UNSPECIFIED"
    SUBMITTED = "TASK_STATE_SUBMITTED"
    WORKING = "TASK_STATE_WORKING"
    COMPLETED = "TASK_STATE_COMPLETED"
    FAILED = "TASK_STATE_FAILED"
    CANCELED = "TASK_STATE_CANCELED"
    INPUT_REQUIRED = "TASK_STATE_INPUT_REQUIRED"
    REJECTED = "TASK_STATE_REJECTED"
    AUTH_REQUIRED = "TASK_STATE_AUTH_REQUIRED"


class Role(str, Enum):
    """Defines the sender of a message in A2A protocol communication."""

    UNSPECIFIED = "ROLE_UNSPECIFIED"
    USER = "ROLE_USER"
    AGENT = "ROLE_AGENT"


# =============================================================================
# Part Types (Content containers)
# =============================================================================


class Part(BaseModel):
    """
    Part represents a container for a section of communication content.
    Parts can be text, file references, or structured data.
    
    A Part MUST contain exactly one of: text, raw, url, data
    """

    text: str | None = None
    raw: bytes | None = None  # Base64-encoded in JSON
    url: str | None = None
    data: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    filename: str | None = None
    mediaType: str | None = Field(None, alias="media_type")

    class Config:
        populate_by_name = True


class TextPart(Part):
    """Convenience class for text-only parts."""

    def __init__(self, text: str, **kwargs):
        super().__init__(text=text, **kwargs)


class DataPart(Part):
    """Convenience class for structured data parts."""

    def __init__(self, data: dict[str, Any], **kwargs):
        super().__init__(data=data, **kwargs)


# =============================================================================
# Core Protocol Objects
# =============================================================================


class Message(BaseModel):
    """
    Message is one unit of communication between client and server.
    
    For server messages, contextId must be provided.
    For client messages, both fields are optional.
    """

    messageId: str = Field(default_factory=lambda: str(uuid.uuid4()))
    contextId: str | None = None
    taskId: str | None = None
    role: Role = Role.USER
    parts: list[Part] = Field(default_factory=list)
    metadata: dict[str, Any] | None = None
    extensions: list[str] | None = None
    referenceTaskIds: list[str] | None = None


class Artifact(BaseModel):
    """
    Artifacts represent task outputs.
    
    These are the results generated by the agent as a result of processing a task.
    """

    artifactId: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str | None = None
    description: str | None = None
    parts: list[Part] = Field(default_factory=list)
    metadata: dict[str, Any] | None = None
    extensions: list[str] | None = None


class TaskStatus(BaseModel):
    """A container for the status of a task."""

    state: TaskState = TaskState.SUBMITTED
    message: Message | None = None
    timestamp: datetime | None = Field(default_factory=datetime.utcnow)


class Task(BaseModel):
    """
    Task is the core unit of action for A2A.
    
    It has a current status and when results are created for the task
    they are stored in artifacts. Multi-turn interactions are stored in history.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    contextId: str = Field(default_factory=lambda: str(uuid.uuid4()))
    status: TaskStatus = Field(default_factory=TaskStatus)
    artifacts: list[Artifact] | None = None
    history: list[Message] | None = None
    metadata: dict[str, Any] | None = None


# =============================================================================
# Streaming Events
# =============================================================================


class TaskStatusUpdateEvent(BaseModel):
    """An event sent by the agent to notify the client of a status change."""

    taskId: str
    contextId: str
    status: TaskStatus
    metadata: dict[str, Any] | None = None


class TaskArtifactUpdateEvent(BaseModel):
    """An event for when an artifact has been generated or updated."""

    taskId: str
    contextId: str
    artifact: Artifact
    append: bool | None = False
    lastChunk: bool | None = False
    metadata: dict[str, Any] | None = None


class StreamResponse(BaseModel):
    """
    A wrapper object used in streaming operations.
    
    A StreamResponse MUST contain exactly one of: task, message, statusUpdate, artifactUpdate
    """

    task: Task | None = None
    message: Message | None = None
    statusUpdate: TaskStatusUpdateEvent | None = None
    artifactUpdate: TaskArtifactUpdateEvent | None = None


# =============================================================================
# Agent Discovery Objects
# =============================================================================


class AgentProvider(BaseModel):
    """Information about the service provider of the agent."""

    organization: str
    url: str | None = None


class AgentCapabilities(BaseModel):
    """Defines optional capabilities supported by an agent."""

    streaming: bool | None = True
    pushNotifications: bool | None = False
    extensions: list[dict[str, Any]] | None = None
    extendedAgentCard: bool | None = False


class AgentSkill(BaseModel):
    """
    Represents a distinct capability or function that an agent can perform.
    
    Skills help clients understand what tasks the agent can handle.
    """

    id: str
    name: str
    description: str
    tags: list[str] = Field(default_factory=list)
    examples: list[str] | None = None
    inputModes: list[str] | None = None
    outputModes: list[str] | None = None


class AgentInterface(BaseModel):
    """
    Declares a combination of target URL, transport, and protocol version.
    
    This allows agents to expose the same functionality over multiple protocol bindings.
    """

    url: str
    protocolBinding: Literal["JSONRPC", "GRPC", "HTTP+JSON"] = "HTTP+JSON"
    tenant: str | None = None
    protocolVersion: str = "1.0"


class AgentCard(BaseModel):
    """
    AgentCard is a self-describing manifest for an agent.
    
    It provides essential metadata including identity, capabilities, skills,
    supported communication methods, and security requirements.
    """

    name: str
    description: str
    supportedInterfaces: list[AgentInterface] = Field(default_factory=list)
    provider: AgentProvider | None = None
    version: str = "1.0.0"
    documentationUrl: str | None = None
    capabilities: AgentCapabilities = Field(default_factory=AgentCapabilities)
    securitySchemes: dict[str, Any] | None = None
    securityRequirements: list[dict[str, Any]] | None = Field(
        default=None, alias="security"
    )
    defaultInputModes: list[str] = Field(
        default_factory=lambda: ["text/plain", "application/json"]
    )
    defaultOutputModes: list[str] = Field(
        default_factory=lambda: ["text/plain", "application/json"]
    )
    skills: list[AgentSkill] = Field(default_factory=list)
    iconUrl: str | None = None

    class Config:
        populate_by_name = True


# =============================================================================
# Request/Response Objects
# =============================================================================


class SendMessageConfiguration(BaseModel):
    """Configuration for a send message request."""

    acceptedOutputModes: list[str] | None = None
    historyLength: int | None = None
    blocking: bool | None = False


class SendMessageRequest(BaseModel):
    """Request payload for SendMessage operation."""

    message: Message
    configuration: SendMessageConfiguration | None = None
    metadata: dict[str, Any] | None = None


class SendMessageResponse(BaseModel):
    """Response payload for SendMessage operation."""

    task: Task | None = None
    message: Message | None = None


class GetTaskRequest(BaseModel):
    """Request payload for GetTask operation."""

    id: str
    historyLength: int | None = None


class ListTasksRequest(BaseModel):
    """Request payload for ListTasks operation."""

    contextId: str | None = None
    status: TaskState | None = None
    pageSize: int | None = 50
    pageToken: str | None = None
    historyLength: int | None = None
    includeArtifacts: bool | None = False


class ListTasksResponse(BaseModel):
    """Response payload for ListTasks operation."""

    tasks: list[Task] = Field(default_factory=list)
    nextPageToken: str = ""
    pageSize: int = 50
    totalSize: int = 0


class CancelTaskRequest(BaseModel):
    """Request payload for CancelTask operation."""

    id: str


# =============================================================================
# Error Types
# =============================================================================


class A2AError(BaseModel):
    """Base error response for A2A protocol errors."""

    type: str
    title: str
    status: int
    detail: str
    taskId: str | None = None
    timestamp: datetime | None = Field(default_factory=datetime.utcnow)


class TaskNotFoundError(A2AError):
    """Error when task is not found."""

    type: str = "https://a2a-protocol.org/errors/task-not-found"
    title: str = "Task Not Found"
    status: int = 404


class UnsupportedOperationError(A2AError):
    """Error when operation is not supported."""

    type: str = "https://a2a-protocol.org/errors/unsupported-operation"
    title: str = "Unsupported Operation"
    status: int = 400


class ContentTypeNotSupportedError(A2AError):
    """Error when content type is not supported."""

    type: str = "https://a2a-protocol.org/errors/content-type-not-supported"
    title: str = "Content Type Not Supported"
    status: int = 415
